version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: daily
      time: '05:00'
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
    groups:
      docker:
        patterns:
          - docker/*
  - package-ecosystem: gradle
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: daily
      time: '05:00'
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
    groups:
      log4j:
        patterns:
          - org.apache.logging.log4j:*
      google-apis:
        patterns:
          - com.google.api-client:google-api-client
          - com.google.apis:*
          - com.google.oauth-client:google-oauth-client-jetty
      exposed:
        patterns:
          - org.jetbrains.exposed:*
