= Viewer
:toc:
:toclevels: 4
:toc: preamble

The main objective of the viewer app is to display the analytics data collected by the miner.

== How to use [[how_to_use]]

=== Clone

Java 17+ is required.

1. Clone this repository `git clone git@github.com:RakSrinaNa/ChannelPointsMiner.git`.
2. Get into the cloned directory `cd ChannelPointsMiner/viewer`.
3. Build the jar `./gradlew build`
4. Run
* Default: `java -jar viewer/build/libs/miner-shaded.jar -Dspring.config.location=file:application-local.yml -Dspring.profiles.active=local`

=== Docker

Image link:https://hub.docker.com/r/mrcraftcod/channel-points-miner-viewer[mrcraftcod/channel-points-miner-viewer,window="_blank"] can be used.

Here's an example dockerfile:

[source,yml]
----
version: "3.9"

services:
  miner:
    image: mrcraftcod/channel-points-miner-viewer:latest
    environment:
        JDK_JAVA_OPTIONS: "-Dspring.config.location=file:/usr/src/app/application-docker.yml -Dspring.profiles.active=docker"
    volumes:
      - ./application-docker.yml:/usr/src/app/application-docker.yml:ro
----

== Settings

You'll have to provide a valid SpringBoot configuration.
In the examples of setup above it is under yml format but can be anything spring accepts.

Especially you'll need to provide a database connection.

Here's an example for MariaDB:

[source,yml]
----
spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3306/ChannelPointsMiner"
    username: "user"
    password: "pass"
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----
